apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: P1809F7CD0C75ACF3
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    editable: true

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    editable: true
